### ISSUE TITLE
Cluster roles to manage backupconfigurations and backupsessions in OpenShift

### ISSUE THREAD

**Issue by timbrd** [stashed/stash#1010]
Since OpenShift is multi-tenant, only the cluster administrator currently is able to manage backupconfigurations and backupsessions. After installing stash, there also were no cluster roles which I could assign to project members to allow the configuration of backup jobs.

I could not find any hints in the documentation, so I have created a few cluster roles, which I'd like to share.

By default, the project admin now can manage all of the backup configurations of the project.
The project admin also can delegate permissions to project members, as expected.

```bash
$ oc adm policy add-role-to-user stash-backupconfiguration-viewer member -n my-project
$ oc adm policy add-role-to-user stash-backupsessions-viewer member -n my-project
```

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stash-backupconfiguration-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["stash.appscode.com"]
  resources: ["backupconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stash-backupconfiguration-viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["stash.appscode.com"]
  resources: ["backupconfigurations"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stash-backupsession-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["stash.appscode.com"]
  resources: ["backupsessions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stash-backupsession-viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["stash.appscode.com"]
  resources: ["backupsessions"]
  verbs: ["get", "list", "watch"]
```
