### ISSUE TITLE
Support templeting hook part

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1034]
Stash hooks can be used to send Slack notification. Here is an example:

![notification](https://user-images.githubusercontent.com/12577390/72730988-e334cc00-3bbc-11ea-81c3-bfc8e3fdfba7.png)

The above notification can be sent by the following hook specification:

```yaml
 hooks:
    preBackup:
      httpPost:
        host: hooks.slack.com
        path: /services/TXXXX/BXXXXXXX/XXXXXXXXXXXXXXXXXXXXXX
        port: 443
        scheme: HTTPS
        httpHeaders:
          - name: Content-Type
            value: application/json
        body: '{
                "blocks": [
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Backup started for *wordpres-backup*.\n *Targets:*\n- deployment/wordpress\n- mysql/wordpress-mysql"
                    }
                  }
                ]
              }'
    postBackup:
      httpPost:
        host: hooks.slack.com
        path: /services/TXXXX/BXXXXXXX/XXXXXXXXXXXXXXXXXXXXXX
        port: 443
        scheme: HTTPS
        httpHeaders:
          - name: Content-Type
            value: application/json
        body: '{
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Backup has been completed for *wordpres-backup*."
                    }
                  }
                ]
              }'
```

Note that here the `body` section is hard coded. It would be nice if user can use `$TARGETS` variable instead of specifying what targets will be backed up and Stash could automatically resolve the variable. Also, it would be possible to send final phase of the backup by resolving a`$PHASE` variable.
