### ISSUE TITLE
postRestore hook can't be executed

### ISSUE THREAD

**Issue by cstaud** [stashed/stash#1055]
In my scenario I have a statefulset with corresponding backupconfiguration. Backups run smoothly also with applied pre- and post hooks. When I apply a RestoreSession I am not able to execute the postRestore hook as there is no container where this command could be executed (beside the init-container/stash-init) where I can run a "delete some file" command.

This RestoreSession:
```
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore
  namespace: demo
spec:
  repository:
    name: demo
  rules:
    - paths:
        - /data
  hooks:
    postRestore:
      exec:
        command:
          - /bin/sh
          - c
          - rm /data/some.file
      containerName: stash-init
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: demo
    volumeMounts:
      - name:  datadir
        mountPath:  /data
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
```

gives this error:
```
ok, when I try to do it this way it leads me into following error:
I0224 09:34:17.612470       1 util.go:485] Executing postRestore hooks.........                                                                                                                
W0224 09:34:18.214967       1 restore.go:239] Failed to complete restore process for RestoreSession restore. Reason: failed to execute "exec" probe. Error: could not execute: command 
terminated with exit code 2. Response: . Warning: The actual restore process may be succeeded. Hence, the restored data might be present in the target even if the overall RestoreSession phase
 is 'Failed'
```

**Comment by pazoozooCH** [comment]
+1
I think in postRestore, the app container should be available, otherwise a lot of use cases will not be possible...

**Comment by Legion2** [comment]
Same here, without the container running the data from the backup can not be imported

**Comment by JcGKitten** [comment]
Hey, is there any solution to this? My postRestore Hook also fails cause the container couldn't be found.

**Comment by piyush1146115** [comment]
@JcGKitten Could you please mention which Stash version you using now?

**Comment by JcGKitten** [comment]
Hello @piyush1146115, thx for the quick reply and sorry for my short initial message.

I'm using Stash v2022.09.29 at the moment and wanted to create a postRestore Hook which runs a command on the started container named `postgres`. 
I specified the name via the `containerName` key word with in the RestoreSession CRD. The sessions then fails because the container with the name couldn't be found. This also happens when I don't set a specific container and it uses the first one.
For BackupSessions this works like a charm but maybe I got something wrong?

Best whishes.

**Comment by piyush1146115** [comment]
Hi @JcGKitten , No worries. Thank you for your detailed reply!

Your Stash version looks recent. We will be looking into the issue very shortly and will let you know once we can figure out the root cause.

**Comment by piyush1146115** [comment]
Hi @JcGKitten,
Could you please verify if you specify your PostRestoreHook like the following works?

```yaml
postRestore:
      exec:
        command: ["/bin/sh", "-c", "echo 'Hello world'"]
      containerName: stash-init
```
