### ISSUE TITLE
Custom image for sidecar container

### ISSUE THREAD

**Issue by fstarkenberg** [stashed/stash#1076]
Hi,

I'm trying to backup to a backend with a self-signed certificate. I could't find a way to include a certificate on run so I decided to build it into the docker image.

I'm using the stash operator in kubernetes and in values I have defined:
```
operator:
  registry: docker.myrepo.net
  repository: mygroup/docker-images/stash-operator
  tag: v0.9.0-rc.6
```
The resulting  image for the operator in kube-system looks correct:  
`image: docker.myrepo.net/mygroup/docker-images/stash-operator:v0.9.0-rc.6`

But the sidecar when running a backup gets some kind of mix of values:  
`image: docker.myrepo.net/stash:v0.9.0-rc.6`

Which of course leads to `Back-off pulling image`.
I've been unable to find where this value is set in the backend.
