### ISSUE TITLE
AWS/EKS:  Use AWS_ROLE_ARN with the token from AWS_WEB_IDENTITY_TOKEN_FILE for accessing Repository (S3)

### ISSUE THREAD

**Issue by ghost** [stashed/stash#1101]
We know how to [create the user and assign proper permissions to s3 bucket](https://restic.readthedocs.io/en/stable/080_examples.html?highlight=iam#setting-up-restic-with-amazon-s3), but it will cause generating and exposing (statically) credentials - `no go`.

We are considering stash as our main/backup restore operator, and I responsible for configuration it with EKS, which got AWS AIM <-> k8s RBAC integration for the last few months.

One of key feature that we follow is **no sensitive data at k8s secret/cm, while we are using EKS**.
I took helm chart latest version and deployed into separate stash namespace (tried with with  own sa for stash as well)
App workload located at default namespace as writer deployment that uses service_account `stash-me-default` to run pods.
[AWS side have properly setup IAM role](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) that associated with k8s sa stash-me-default via annotation `"eks.amazonaws.com/role-arn: xxx"`
I can confirm that token appeared in pod and stash container has read access to it
```
k exec -it writer-59cc45f5d8-gpxgf -c stash env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::123456:role/9a3s-default-tm-stash20200507162055918200000002
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
Hovewer, I got client.PutObject: Access Denied for S3 operation by stash backupsession.
```
0s          Normal    Started                            pod/stash-backup-me-test-ebs-backup-config-1588956060-k6g97   Started container stash
0s          Normal    BackupSession Running              backupsession/me-test-ebs-backup-config-1588956066            Backup job has been created succesfully/sidecar is watching the BackupSession.
0s          Warning   Host Backup Failed                 backupsession/me-test-ebs-backup-config-1588956066            backup failed for host "host-0" of "Deployment"/"writer". Reason: failed to complete backup for host host-0. Reason: Fatal: create key in repository at s3:s3.amazonaws.com/my_bucket_name/backup/demo failed: client.PutObject: Access Denied
0s          Warning   BackupSession Failed               backupsession/me-test-ebs-backup-config-1588956066            Backup session failed to complete. Reason: backup failed for target: Deployment/writer
0s          Normal    MissingJob                         cronjob/stash-backup-me-test-ebs-backup-config                Active job went missing: stash-backup-me-test-ebs-backup-config-1588956060
```
I am able to execute `aws s3 ls` at same pod without AWS secrets in k8s and operate with AWS based on `sa` role.
But stash definitely ignores env in the way how AWS cli proceed.

Please add the feature for Stash/Restic to use AWS_ROLE_ARN with the token from AWS_WEB_IDENTITY_TOKEN_FILE for accessing Repository (AWS S3) based on [AWS SDK for GO](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/)

Thank you
RJ

**Comment by roman-judin-dragon** [comment]
It is one of the cases from https://github.com/stashed/stash/issues/711

**Comment by roman-judin-dragon** [comment]
Current issue related to minio SDK that used at restic https://github.com/vmware-tanzu/velero/issues/2198

**Comment by whereisaaron** [comment]
This  support is coming for `restic`.
https://github.com/restic/restic/issues/2703#issuecomment-627925148
https://github.com/restic/restic/pull/2733

**Comment by hossainemruz** [comment]
Stash `v0.11.x+` already works with IAM.

**Setting IAM Permission for a ServiceAccount:**  
- https://docs.amazonaws.cn/en_us/eks/latest/userguide/iam-roles-for-service-accounts.html

**Service Account:**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-accessor
  namespace: demo
  labels:
    app: stash-demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>
```

**Workload:**
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stash-sample-data
  namespace: demo
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: stash-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      serviceAccountName: bucket-accessor
      containers:
      - args: ["echo sample_data > /source/data/data.txt && sleep 3000"]
        command: ["/bin/sh", "-c"]
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: stash-sample-data
      securityContext:
        runAsUser: 0
        runAsGroup: 0
```

**Backend Secret:**
Just provide `RESTIC_PASSWORD` during creating the repository secret.  For example,

```bash
$  echo -n 'changeit' > RESTIC_PASSWORD
$ kubectl create secret generic -n demo minio-secret \
      --from-file=./RESTIC_PASSWORD
```

```yaml
❯ kubectl get secret -n demo s3-secret -o yaml
apiVersion: v1
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
kind: Secret
metadata:
  creationTimestamp: "2021-02-22T12:00:41Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:RESTIC_PASSWORD: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-02-22T12:00:41Z"
  name: s3-secret
  namespace: demo
  resourceVersion: "2209120"
  selfLink: /api/v1/namespaces/demo/secrets/s3-secret
  uid: f7b38e76-20ce-416c-b53a-e33244f0b743
type: Opaque
```

**Repository:**
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      endpoint: s3.amazonaws.com
      bucket: stash-qa
      region: us-east-1
      prefix: /stash/iam-demo
    storageSecretName: s3-secret
```

**BackupConfiguration:**

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
  runtimeSettings:
    pod:
      serviceAccountName: bucket-accessor
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

**Environment variables inside `stash` sidecar:**
```bash
❯ kubectl exec -n demo stash-demo-56478d64b6-fgl5m -c stash -- /bin/sh -c env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::<AWS_USER_ID>:role/<IAM_ROLE_NAME>
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_DEFAULT_REGION=us-west-2
AWS_REGION=us-west-2
```

**BackupSession:**
```bash
❯ kubectl get backupsession -n demo
NAME                           INVOKER-TYPE          INVOKER-NAME        PHASE       AGE
deployment-backup-1614003607   BackupConfiguration   deployment-backup   Succeeded   2m49s
```
