### ISSUE TITLE
Unable to install stash 0.9.0-rc.6 in PSP-enabled cluster

### ISSUE THREAD

**Issue by uipo78** [stashed/stash#1112]
## System details
stash version: `0.9.0-rc.6`
k8s version: `1.16.3`

## Steps to reproduce
[Follow the setup instructions using the default values](https://stash.run/docs/v0.9.0-rc.6/setup/install/).

## What I expected to see
The stash operator deployed without any configuration errors.

## What I saw
After running `helm install [...]`, we see this:
```
NAME                              READY   STATUS                       RESTARTS   AGE
stash-operator-7f46d68cb5-vgdbr   1/2     CreateContainerConfigError   0          2m27s
```

Running `kubectl describe pod [...]`, we see this:
```yaml
$ k describe pod stash-operator-7f46d68cb5-vgdbr -n stash
Name:           stash-operator-7f46d68cb5-vgdbr
Namespace:      stash
Priority:       0
Node:           aks-akspool-26081535-vmss0000h5/10.0.0.4
Start Time:     Wed, 20 May 2020 11:45:28 -0500
Labels:         app=stash
                chart=stash-v0.9.0-rc.6
                heritage=Helm
                pod-template-hash=7f46d68cb5
                release=stash-operator
Annotations:    container.apparmor.security.beta.kubernetes.io/operator: runtime/default
                container.apparmor.security.beta.kubernetes.io/pushgateway: runtime/default
                kubernetes.io/psp: restricted
                seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:         Pending
IP:             10.0.0.46
IPs:            <none>
Controlled By:  ReplicaSet/stash-operator-7f46d68cb5
Containers:
  operator:
    Container ID:  docker://ef3b390529d538aae858553a4e07f15721f4a0e8a5eba93778e7519ef03c4881
    Image:         appscode/stash:v0.9.0-rc.6
    Image ID:      docker-pullable://appscode/stash@sha256:f312f8be0cda80ff2fe42ec267a4c6b86db6b055073e2852dd621b8adc2ae6ed
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      run
      --v=3
      --docker-registry=appscode
      --image-tag=v0.9.0-rc.6
      --secure-port=8443
      --audit-log-path=-
      --tls-cert-file=/var/serving-cert/tls.crt
      --tls-private-key-file=/var/serving-cert/tls.key
      --service-name=stash-operator
      --enable-mutating-webhook=true
      --enable-validating-webhook=true
      --bypass-validating-webhook-xray=false
      --use-kubeapiserver-fqdn-for-aks=true
      --enable-analytics=false
    State:          Running
      Started:      Wed, 20 May 2020 11:45:30 -0500
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment:
      MY_POD_NAME:       stash-operator-7f46d68cb5-vgdbr (v1:metadata.name)
      MY_POD_NAMESPACE:  stash (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from stash-operator-token-7dj6p (ro)
      /var/serving-cert from serving-cert (rw)
  pushgateway:
    Container ID:  
    Image:         prom/pushgateway:v0.5.2
    Image ID:      
    Port:          56789/TCP
    Host Port:     0/TCP
    Args:
      --web.listen-address=:56789
      --persistence.file=/var/pv/pushgateway.dat
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp from stash-scratchdir (rw)
      /var/pv from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from stash-operator-token-7dj6p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  stash-scratchdir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  stash-operator-apiserver-cert
    Optional:    false
  stash-operator-token-7dj6p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  stash-operator-token-7dj6p
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/arch=amd64
                 beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                                      Message
  ----     ------     ----                   ----                                      -------
  Normal   Scheduled  3m34s                  default-scheduler                         Successfully assigned stash/stash-operator-7f46d68cb5-vgdbr to aks-akspool-26081535-vmss0000h5
  Normal   Pulled     3m32s                  kubelet, aks-akspool-26081535-vmss0000h5  Container image "appscode/stash:v0.9.0-rc.6" already present on machine
  Normal   Created    3m32s                  kubelet, aks-akspool-26081535-vmss0000h5  Created container operator
  Normal   Started    3m32s                  kubelet, aks-akspool-26081535-vmss0000h5  Started container operator
  Normal   Pulled     107s (x11 over 3m32s)  kubelet, aks-akspool-26081535-vmss0000h5  Container image "prom/pushgateway:v0.5.2" already present on machine
  Warning  Failed     107s (x11 over 3m32s)  kubelet, aks-akspool-26081535-vmss0000h5  Error: container has runAsNonRoot and image will run as root
```

Take note of the annotation `kubernetes.io/psp: restricted` -- the problem in this issue is likely related to [this issue's](https://github.com/stashed/stash/issues/910).
