### ISSUE TITLE
Single BackupBatch makes stash think Repository does not exist

### ISSUE THREAD

**Issue by endrec** [stashed/stash#1113]
I am using stash 0.9.6-rc.6
I have a Repository pointing to an s3 bucket, and a BackupBatch with two targets, both are referenced via AppBindings (two kubedb databases).
Backups are created fine, but stash logs the following in every 10 minutes or so (which is the same as my schedule in the BackupBatch):

```
[golang-sh]$ /bin/restic_0.9.6 snapshots --json --quiet --no-lock --no-cache
Fatal: unable to open config file: Stat: The specified key does not exist.
Is there a repository at the following location?
s3:s3.amazonaws.com/XXX
```

The message is correct in that sense that I don't have a config file in the repository "root", only in `appbindings/<name>`.

If I create a BackupConfiguration, which targets one of the two AppBindings included in the batch, it will create a snapshot in the repository root, and the fatal error stops.

**Comment by endrec** [comment]
Also, Snapshots taken by BackupBatch are NOT listed with `kubectl get snapshots` (though they are correctly included in snapshot-count for the repository):

```
➜ kubectl get repository -A
NAMESPACE   NAME        INTEGRITY   SIZE        SNAPSHOT-COUNT   LAST-SUCCESSFUL-BACKUP   AGE
rungway     s3-backup   true        2.296 TiB   181              63s                      11d

➜ kubectl get backupbatch -A
NAMESPACE   NAME          SCHEDULE       PAUSED   AGE
rungway     data-backup   */10 * * * *            11d

➜ kubectl get backupconfiguration -A
NAMESPACE   NAME              TASK                   SCHEDULE      PAUSED   AGE
rungway     postgres-backup   postgres-backup-10.2   53 16 * * *            8d

➜ kubectl get snapshots -A -o wide
NAMESPACE   NAME                 AGE
rungway     s3-backup-5f30b677   4d23h
rungway     s3-backup-28420d06   3d23h
rungway     s3-backup-5a0bd81e   2d23h
rungway     s3-backup-318fe270   47h
rungway     s3-backup-8b0273c8   23h
```

**Comment by hossainemruz** [comment]
Hi @endrec can you please check the respective jobs for the two targets and inform us what is the value for this flag?
https://github.com/stashed/postgres/blob/cd9a3b1fa79ed41d52bfed3e6f82c69285c69121/pkg/backup.go#L108

**Comment by endrec** [comment]
Hi @hossainemruz,

The `Backupbatch`:
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
[...]
spec:
  members:
  - target:
      ref:
        apiVersion: appcatalog.appscode.com/v1alpha1
        kind: AppBinding
        name: postgres
    task:
      name: postgres-backup-10.2
  - target:
      ref:
        apiVersion: appcatalog.appscode.com/v1alpha1
        kind: AppBinding
        name: mongo
    task:
      name: mongodb-backup-3.6
  repository:
    name: s3-backup
[...]
```

Creates two jobs:
```
[...]
      initContainers:
      - args:
        - backup-pg
[...]
        - --path=/k8s-dev/stash-backup//appbinding/postgres
[...]
        image: stashed/stash-postgres:10.2
[...]
```
and
```
[...]
      initContainers:
      - args:
        - backup-mongo
[...]
        - --path=/k8s-dev/stash-backup//appbinding/mongo
[...]
        image: stashed/stash-mongodb:3.6
[...]
```

On the other hand, the job from a `Backupconfiguration' 
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
[...]
spec:
  repository:
    name: s3-backup
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
  task:
    name: postgres-backup-10.2
[...]
```

has this in its job:
```
[...]
      initContainers:
      - args:
        - backup-pg
[...]
        - --path=/k8s-dev/stash-backup/
[...]
        image: stashed/stash-postgres:10.2
[...]
```

**Comment by hossainemruz** [comment]
Can you please show your Repository YAML?

**Comment by endrec** [comment]
```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
[...]
spec:
  backend:
    s3:
      bucket: XXXX
      endpoint: s3.amazonaws.com
      prefix: /k8s-dev/stash-backup/
      region: eu-west-1
    storageSecretName: s3-backup
status:
  firstBackupTime: "2020-05-18T14:00:29Z"
  integrity: true
  lastBackupTime: "2020-06-01T09:52:50Z"
  snapshotCount: 185
  totalSize: 2.342 TiB
```
