### ISSUE TITLE
BackupBlueprint: multiple schedule times?

### ISSUE THREAD

**Issue by remoe** [stashed/stash#1131]
How one can create a BackupBlueprint with multiple schedule times? My idea was:

```yaml
kind: BackupBlueprint
metadata:
  name: pvc-autobackup-5min
schedule: "*/5 * * * *"
---
kind: BackupBlueprint
metadata:
  name: pvc-autobackup-daily
schedule: "0 3 * * *"
---
kind: BackupBlueprint
metadata:
  name: pvc-autobackup-monthly
schedule: "0 0 1 * *"
```

But how can i add multiple shedule BackupBlueprint to pvc?

The following is not possible:

```yaml
  annotations:
    stash.appscode.com/backup-blueprint: pvc-autobackup-daily
    stash.appscode.com/backup-blueprint: pvc-autobackup-monthly
```

Or does have ```stash``` another way to do this?

**Comment by hossainemruz** [comment]
Why do you need multiple schedule for a single PVC? You can just have daily backup and configure `retentionPolicy` to keep daily and monthly backup.
- https://stash.run/docs/v0.9.0-rc.6/concepts/crds/backupconfiguration/#specretentionpolicy

```yaml
retentionPolicy:
    name: keep-daily-weekly-monthly,
    keepDaily: 5,
    keepWeekly: 4,
    keepMonthly: 2,
    prune: true
```
