### ISSUE TITLE
Stash Can't inject backup sidecar

### ISSUE THREAD

**Issue by jepangLee** [stashed/stash#1217]
I Followed this [guide](https://stash.run/docs/v2020.09.29/guides/latest/workloads/statefulset/)

Kubernetes version: v1.17.9-eks-4c6976
stash community version: v0.11.2

- persistantVolumeClaim/mysql-pvc

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-pvc
      namespace: test-backup
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: csi-ebs-gp2-sc
    ```

- stateful_set/mysql_sts

    ```yaml
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mysql-sts
      namespace: test-backup
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mysql
      serviceName: ""
      template:
        metadata:
          labels:
            app: mysql
        spec:
          initContainers:
            - env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
              image: ubuntu:16.04
              name: remove-lost-found
              command: [
                "sh",
                "-c",
                "chown -R 999:999 /var/lib/mysql; rm -fr /var/lib/mysql/lost+found;"
              ]
              volumeMounts:
                - mountPath: /var/lib/mysql
                  name: mysql-data
          containers:
            - env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
              image: mysql:8.0.15
              imagePullPolicy: IfNotPresent
              name: mysql
              ports:
                - containerPort: 3306
                  protocol: TCP
              resources:
                limits:
                  cpu: 512m
                  memory: 512Mi
                requests:
                  cpu: 256m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /var/lib/mysql
                  name: mysql-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: mysql-data
              persistentVolumeClaim:
                claimName: mysql-pvc
    ```

   ![Screen Shot 2020-10-07 at 3 23 40 PM](https://user-images.githubusercontent.com/38655928/95295083-64e69a00-08b1-11eb-8e9a-1820e652a8f5.png)

- Secret/gcs-secret

    ```bash
    kubectl create secret generic -n test-backup gcs-secret \
        --from-file=./RESTIC_PASSWORD \
        --from-file=./GOOGLE_PROJECT_ID \
        --from-file=./GOOGLE_SERVICE_ACCOUNT_JSON_KEY
    ```

- Repositories.stash.appscode.com/mysql-repo

    ```yaml
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: mysql-repo
      namespace: test-backup
    spec:
      backend:
        gcs:
          bucket: jepang-mysql-data
          prefix: /mysql
        storageSecretName: gcs-secret
    ```

- BackupConfigurations.stash.appscode.com/mysql-bc

    ```yaml
    apiVersion: stash.appscode.com/v1beta1
    kind: BackupConfiguration
    metadata:
      name: mysql-bc
      namespace: test-backup
    spec:
      repository:
        name: mysql-repo
      schedule: "* */5 * * *"
      target:
        ref:
          apiVersion: apps/v1
          kind: StatefulSet
          name: mysql-sts
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
        paths:
          - /mysql
      retentionPolicy:
        name: 'keep-last-5'
        keepLast: 5
        prune: true
    ```

Why can't stash inject sidecar in pod?
