### ISSUE TITLE
Failed to read all source data during backup

### ISSUE THREAD

**Issue by svua** [stashed/stash#1243]
kubernetis version v1.18.3 on the bare metal
Minio for repository
stash was installed:
```
helm upgrade stash-operator appscode/stash -n stash --set-file license=stash-community-license...
```
I tried to backup from this link https://stash.run/docs/v2020.08.27/guides/latest/workloads/deployment/
It didn't work.
Also I tried to backup from this link https://youtu.be/yhr8n-UYcgo
It also didn't work.

I got the same messages in both cases.


```
k describe backupsessions.stash.appscode.com
...
   Stats:
      Error:      failed to complete backup for host host-1. Reason: {"message_type":"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival","item":"/my/data/lost+found"} Warning: failed to read all source data during backup
      Hostname:   host-1
      Phase:      Failed
      Error:      failed to complete backup for host host-0. Reason: {"message_type":"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival","item":"/my/data/lost+found"} Warning: failed to read all source data during backup
      Hostname:   host-0
      Phase:      Failed
    Total Hosts:  2
Events:
  Type     Reason                 Age   From                      Message
  ----     ------                 ----  ----                      -------
  Normal   BackupSession Running  56s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Normal   BackupSession Running  56s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Normal   BackupSession Running  55s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Warning  Host Backup Failed     54s   Status Updater            backup failed for host "host-1" of "StatefulSet"/"stash-demo". Reason: failed to complete backup for host host-1. Reason: {"message_type":"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival","item":"/my/data/lost+found"} Warning: failed to read all source data during backup
  Warning  BackupSession Failed   54s   BackupSession Controller  Backup session failed to complete. Reason: backup failed for target: StatefulSet/stash-demo
  Warning  Host Backup Failed     37s   Status Updater            backup failed for host "host-0" of "StatefulSet"/"stash-demo". Reason: failed to complete backup for host host-0. Reason: {"message_type":"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival","item":"/my/data/lost+found"} Warning: failed to read all source data during backup
```
```

k describe backupsession.stash.appscode.com/ss-backup-1604440807                                                                      
Name:         ss-backup-1604440807                                                                                                                                                                         
Namespace:    demo                                                                                                                                                                                         
Labels:       app.kubernetes.io/component=stash-backup                                                                                                                                                     
              app.kubernetes.io/managed-by=stash.appscode.com                                                                                                                                              
              stash.appscode.com/invoker-name=ss-backup                                                                                                                                                    
              stash.appscode.com/invoker-type=BackupConfiguration                                                                                                                                          
Annotations:  <none>                                                                                                                                                                                       
API Version:  stash.appscode.com/v1beta1                                                                                                                                                                   
Kind:         BackupSession                                                                                                                                                                                
Metadata:                                                                                                                                                                                                  
  Creation Timestamp:  2020-11-03T22:00:07Z                                                                                                                                                                
  Generation:          1                                                                                                                                                                                   
  Managed Fields:                                                                                                                                                                                          
    API Version:  stash.appscode.com/v1beta1                                                                                                                                                               
    Fields Type:  FieldsV1                                                                                                                                                                                 
    fieldsV1:                                                                                                                                                                                              
      f:metadata:                                                                                                                                                                                          
        f:labels:                                                                                                                                                                                          
          .:                                                                                                                                                                                               
          f:app.kubernetes.io/component:                                                                                                                                                                   
          f:app.kubernetes.io/managed-by:                                                                                                                                                                  
          f:stash.appscode.com/invoker-name:                                                                                                                                                               
          f:stash.appscode.com/invoker-type:                                                                                                                                                               
        f:ownerReferences:                                                                                                                                                                                 
          .:                                                                                                                                                                                               
          k:{"uid":"bc0da028-a803-4b7a-bf1b-b8ed243d3c6d"}:                                                                                                                                                
            .:                                                                                                                                                                                             
            f:apiVersion:                                                                                                                                                                                  
            f:blockOwnerDeletion:                                                                                                                                                                          
            f:controller:                                                                                                                                                                                  
            f:kind:                                                                                                                                                                                        
            f:name:                                                                                                                                                                                        
            f:uid:
      f:spec:
        .:
        f:invoker:
          .:
          f:apiGroup:
          f:kind:
          f:name:
      f:status:
        .:
        f:conditions:
        f:phase:
        f:targets:
    Manager:    stash
    Operation:  Update
    Time:       2020-11-03T22:00:08Z

    Owner References:
    API Version:           stash.appscode.com/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  BackupConfiguration
    Name:                  ss-backup
    UID:                   bc0da028-a803-4b7a-bf1b-b8ed243d3c6d
  Resource Version:        122239913
  Self Link:               /apis/stash.appscode.com/v1beta1/namespaces/demo/backupsessions/ss-backup-1604440807
  UID:                     748762cb-1710-405d-b172-a350dc033604
Spec:
  Invoker:
    API Group:  stash.appscode.com
    Kind:       BackupConfiguration
    Name:       ss-backup
Status:
  Conditions:
    Last Transition Time:  2020-11-03T22:00:07Z
    Message:               Repository exist in the backend.
    Reason:                BackendRepositoryFound
    Status:                True
    Type:                  BackendRepositoryInitialized
  Phase:                   Failed
  Targets:
    Phase:  Failed
    Post Backup Actions:
      ApplyRetentionPolicy
      VerifyRepositoryIntegrity
      SendRepositoryMetrics
    Pre Backup Actions:
      InitializeBackendRepository
    Ref:
      API Version:  apps/v1
      Kind:         StatefulSet
      Name:         stash-demo
    Stats:
      Error:      failed to complete backup for host host-0. Reason: {"message_type":"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival
","item":"/my/data/lost+found"} Warning: failed to read all source data during backup
      Hostname:   host-0
      Phase:      Failed
    Total Hosts:  1
Events:
  Type     Reason                 Age   From                      Message
  ----     ------                 ----  ----                      -------
  Normal   BackupSession Running  39s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Normal   BackupSession Running  39s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Normal   BackupSession Running  39s   BackupSession Controller  Backup job has been created succesfully/sidecar is watching the BackupSession.
  Warning  Host Backup Failed     38s   Status Updater            backup failed for host "host-0" of "StatefulSet"/"stash-demo". Reason: failed to complete backup for host host-0. Reason: {"message_type"
:"error","error":{},"during":"scan","item":"/my/data/lost+found"} {"message_type":"error","error":{},"during":"archival","item":"/my/data/lost+found"} Warning: failed to read all source data during backu
p
  Warning  BackupSession Failed   38s   BackupSession Controller  Backup session failed to complete. Reason: backup failed for target: StatefulSet/stash-demo
```

statefulset.yaml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stash-demo
  namespace: demo
  labels:
    app: stash-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  serviceName: headless
  template:
    metadata:
      labels:
        app: stash-demo
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c","sleep 3000"]
        env:
        - name:  POD_NAME
          valueFrom:
            fieldRef:
              fieldPath:  metadata.name
        volumeMounts:
        - name: data-volume
          mountPath: /my/data
        imagePullPolicy: IfNotPresent
      nodeSelector:
        destiny: storage
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "standard"
      #storageClassName: "openebs-cstor-r3"
      storageClassName: "local-disks"
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 0
  selector:
    app: stash-demo
  clusterIP: None
```

repository.yaml
```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      endpoint: http://minio-service.cold-data.svc.cluster.local:9000
      bucket: stash
      #region: us-east-1
      prefix: /backup/demo/statefulset/stash-demo
    storageSecretName: s3-secret
```

backupconfiguration.yaml
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: ss-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/3 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stash-demo
    volumeMounts:
    - name: data-volume
      mountPath: /my/data
    paths:
    - /my/data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

**Comment by hossainemruz** [comment]
Can you exec into the StatefulSet and run `ls -lah /my/data`? Since Sash runs as `non-root` user, I believe Stash does not have permission to read the files. In this case, you can run Stash as `root` user by adding `runtimeSettings` in the BackupConfiguration. 

Your final BackupConfiguration should be,

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: ss-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/3 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stash-demo
    volumeMounts:
    - name: data-volume
      mountPath: /my/data
    paths:
    - /my/data
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```
