### ISSUE TITLE
Monitoring does not install

### ISSUE THREAD

**Issue by benalexau** [stashed/stash#1244]
I have freshly installed [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) via the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack). Details:

```
$ helm list -n monitoring
NAME      	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
prometheus	monitoring	1       	2020-11-03 13:48:39.16853579 +1100 AEDT	deployed	kube-prometheus-stack-11.0.0	0.43.0
```

I then installed Stash as follows:

```
$ helm install stash appscode/stash \
  --namespace stash \
  --set-file license=license.txt \
  --set monitoring.agent=prometheus.io/operator \
  --set monitoring.backup=true \
  --set monitoring.operator=true \
  --set monitoring.prometheus.namespace=monitoring \
  --set monitoring.serviceMonitor.labels.k8s-app=prometheus
```

Verified with:

```
$ helm list -n stash
NAME 	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART        	APP VERSION
stash	stash    	1       	2020-11-03 13:58:38.267354777 +1100 AEDT	deployed	stash-v0.11.5	v0.11.5
```

The [Stash Monitoring Instructions](https://stash.run/docs/v2020.10.30/guides/latest/monitoring/coreos/) state the following command should work, but it instead displays the output shown:

```
$ kubectl get servicemonitor stash-servicemonitor -n monitoring -o yaml
Error from server (NotFound): servicemonitors.monitoring.coreos.com "stash-servicemonitor" not found
```

More generally service monitors are found:

```
$ kubectl get servicemonitor -n monitoring        
NAME                                                 AGE
prometheus-kube-prometheus-coredns                   23h
prometheus-kube-prometheus-node-exporter             23h
prometheus-kube-prometheus-prometheus                23h
prometheus-kube-prometheus-grafana                   23h
prometheus-kube-prometheus-kube-state-metrics        23h
prometheus-kube-prometheus-kube-controller-manager   23h
prometheus-kube-prometheus-apiserver                 23h
prometheus-kube-prometheus-kube-etcd                 23h
prometheus-kube-prometheus-kube-proxy                23h
prometheus-kube-prometheus-kubelet                   23h
prometheus-kube-prometheus-kube-scheduler            23h
prometheus-kube-prometheus-alertmanager              23h
prometheus-kube-prometheus-operator                  23h
```

Both Stash and Prometheus work. However Prometheus does not include any Stash metrics.

Is there a known issue with the chart or should I try something else?

**Comment by hossainemruz** [comment]
@benalexau The monitoring doc is outdated. We no longer create ServiceMonitor in the provided namespace. Instead, we create the ServiceMonitor in the operator namespace (`kube-system`). 

Now, your Prometheus CRD should be
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      k8s-app: prometheus
  serviceMonitorNamespaceSelector: {}
```

**Comment by benalexau** [comment]
Thanks @hossainemruz.

> We no longer create ServiceMonitor in the provided namespace. Instead, we create the ServiceMonitor in the operator namespace (kube-system).

In my install it was created in the `stash` namespace (not `kube-system`):

```
$ kubectl get servicemonitor -n stash
NAME    AGE
stash   43h
```

Discovery worked by adding the following additional values to the `kube-prometheus-stack` install:

```yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false 
```
