### ISSUE TITLE
Add documentation clarifying when and how to run Stash as root user

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1257]
**When:**
- NFS as Backend or volume
- hostPath as backend or volume
- Data is not readable by Stash default user.

**How:**
Add `securityContext` under `runtimeSettings` as below:

```yaml
runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
```

Example:

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: ss-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/3 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stash-demo
    volumeMounts:
    - name: data-volume
      mountPath: /my/data
    paths:
    - /my/data
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```
