### ISSUE TITLE
Add separate documentation about how to exclude/include subset of files during backup/restore process

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1262]
This doc should show the following examples:
- [ ] Exclude some files during backup. (using `exclude`)
- [ ] Exclude some files during restore. ( using `exclude`)
- [ ] Only restore selected files during restore. (using `include`)

**Comment by hossainemruz** [comment]
## Example of excluding files during backup

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: demo
spec:
  repository:
    name: gcs-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
    exclude:
    - /source/data/not-important.txt # exclude only one file
    - /source/data/*.html # exclude all file that has a particular extension
    - /source/data/tmp/* # exclude a directory
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

**Comment by hossainemruz** [comment]
### Example of excluding files during restore

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: deployment-restore
  namespace: demo
spec:
  repository:
    name: gcs-repo
  target: # target indicates where the recovered data will be stored
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-recovered
    volumeMounts:
    - name:  source-data
      mountPath:  /source/data
    rules:
    - paths:
      - /source/data/
      exclude:
      - /source/data/tmp.json # don't restore this file
      - /source/data/*.txt # don't restore all file with .txt extension
      - /source/data/* # don't restore this directory
```

**Comment by hossainemruz** [comment]
## Example of restoring only selected files

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: deployment-restore
  namespace: demo
spec:
  repository:
    name: gcs-repo
  target: # target indicates where the recovered data will be stored
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-recovered
    volumeMounts:
    - name:  source-data
      mountPath:  /source/data
    rules:
    - paths:
      - /source/data/
      include:
      - /source/data/tmp.json # restore this file
      - /source/data/*.txt # restore all files with .txt extension
      - /source/data/* # restore this directory
```

All other files in the backed up data won't be restored.
