### ISSUE TITLE
Add configurable retry options

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1279]
Sometimes backup may fail for network issue. In such cases, user expect to retry the backup. This retry logic should be configurable by the user. By default, Stash shouldn't retry. When, user will configure the retry logic, Stash will retry the backup.

There could be some config like this in the BackupConfiguration spec

```yaml
failurePolicy: Retry # default is "Fail"
retryConfig:
  maxRetry: 2
  delay: 10m
```
