### ISSUE TITLE
Elasticsearch migration 

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1296]
- Don't  use single code in `ignoreType` or `includeType`.
i.e.
```yaml
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: styra-data-es-restore
  namespace: styra-data
  labels:
    app.kubernetes.io/name: elasticsearches.kubedb.com
spec:
  task:
    name: elasticsearch-restore-6.8.0-v5
    params:
    - name: args
      value: --ignoreType=settings,alias,template,mapping
  repository:
    name: stash-styra-data-es
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: styra-es
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 1000810000
  interimVolumeTemplate:
    metadata:
      name: stash-tmp-restore-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "netapp-nfs"
      resources:
        requests:
          storage: 100Gi
  rules:
  - snapshots: [latest]
```
- Use regex to ignore particular indexes (i.e. SearchGuard settings)
```
--match='^.*$' \
```
