### ISSUE TITLE
Can`t recover from PVC backend

### ISSUE THREAD

**Issue by holooloo** [stashed/stash#1297]
Hello.
I have a problem with recovery process:
  - i was created a sample deployment from docs
  - then i was created local repository with pvc backend
  - successfully backup with backupsession from docs
  - i was creted a deployment with pvc to recover into it (with paused backup patch)
  - after creating restoresession, i have an error in stash operator logs: 
**failed to update Deployment portal-dev/stash-recovered. Reason: Deployment.apps "stash-recovered" is invalid: spec.template.spec.initContainers[0].volumeMounts[3].name: Not found: "stash-repo"**

stash-repo is a name of my repository!

All manifests from: https://stash.run/docs/v2020.08.27/guides/latest/workloads/deployment/

serviceAccountName: nginx-deployment  -- cluster-admin

What i`ve done wrong?

```
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: portal-dev
spec:
  repository:
    name: stash-repo
  runtimeSettings:
    container:
       securityContext:
        runAsUser: 0
        runAsGroup: 0
  schedule: "*/1 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: stash-demo
  namespace: portal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - args: ["echo sample_data > /source/data/data.txt && sleep 3000"]
        command: ["/bin/sh", "-c"]
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      serviceAccountName: nginx-deployment
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: stash-sample-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-sample-data
  namespace: portal-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-repo
  namespace: portal-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs

---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: stash-repo
  namespace: portal-dev
spec:
  backend:
    local:
      mountPath: /safedata
      persistentVolumeClaim:
        claimName: stash-repo
    storageSecretName: local-secret

---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: deployment-restore
  namespace: portal-dev
spec:
  repository:
    name: stash-repo
  target: # target indicates where the recovered data will be stored
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-recovered
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    rules:
    - paths:
      - /source/data/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: portal-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-recovered
  name: stash-recovered
  namespace: portal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-recovered
  template:
    metadata:
      labels:
        app: stash-recovered
      name: busybox
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: demo-pvc
```
