### ISSUE TITLE
PostgreSQL Customization Examples

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1313]
**Exclude table during backup**
```
task:
  name: postgres-backup-13.1.0-v1
  params:
    name: args
    value: --exclude-table=table
```

**Comment by hossainemruz** [comment]
## Overwrite Backup Command
By default it uses `pg_dumpall`. We can overwrite the command as bellow,

```yaml
task:
  name: postgres-backup-13.1.0-v1
  params:
  - name: backupCMD
    value: pg_dump
```
