### ISSUE TITLE
Getting /bin/restic: invalid argument while trying to backup statefulset to s3

### ISSUE THREAD

**Issue by leitmedium** [stashed/stash#1345]
Hi,

after testing for quite a while I got stuck with the following error: stash community installs fine via helm, it reads it's configuration, deploys a sidecare to a statefulset but is not able to backup and throws a "/bin/restic: invalid argument" error message which leads me to the assumption that my configuration is wrong:

```
I0504 14:57:04.606974       1 commands.go:98] Checking whether the backend repository exist or not....
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
I0504 14:57:04.607564       1 commands.go:109] Initializing new restic repository in the backend....
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
W0504 14:57:04.618997       1 backupsession.go:487] Failed to take backup for BackupSession stash-backup-1620140224. Reason: fork/exec /bin/restic: invalid argument
I0504 14:57:04.619016       1 status.go:115] Updating post backup status.......
W0504 14:57:04.641007       1 backupsession.go:413] failed to complete backup. Reason: fork/exec /bin/restic: invalid argument
```

As I tested different backends and configurations and also did not find somebody with this specific issue, I'll leave my current anonymized configuration here. 

helm install:

```bash
helm install stash appscode/stash -n kube-system --version v2021.04.12 --set features.community=true --set-file global.license=./stash-license.txt
```

secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: stash-secret
  namespace: test
data:
  AWS_ACCESS_KEY_ID: SECRET
  AWS_SECRET_ACCESS_KEY: SECRET
  RESTIC_PASSWORD: SECRET
```

repo.yaml
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: stash-repo
  namespace: test
spec:
  backend:
    s3:
      endpoint: s3.amazonaws.com
      bucket: test-backup
      prefix: /backup
    storageSecretName: stash-secret
```

backup.yaml
```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: stash-backup
  namespace: test
spec:
  repository:
    name: stash-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stateful-name
    volumeMounts:
    - name: data
      mountPath: /data
    paths:
    - /data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

**Comment by hossainemruz** [comment]
@leitmedium Can you please show the YAML of the targeted StatefulSet with Stash sidecar?

**Comment by leitmedium** [comment]
Hi @hossainemruz,

sure! I tidied it up a bit for data security reasons and general readability. If something crucial is missing, let me know:

```yaml
apiVersion: apps/v1
kind: StatefulSet
  name: stateful-name
  namespace: test
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stateful-name
  serviceName: stateful-name
  template:
    metadata:
      annotations:
        stash.appscode.com/last-applied-backup-invoker-hash: "17243268668152049263"
      creationTimestamp: null
      labels:
        app: stateful-name
    spec:
      containers:
        image: stateful-name
        imagePullPolicy: IfNotPresent
        name: go-client
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      - args:
        - run-backup
        - --invoker-name=stash-backup
        - --invoker-kind=BackupConfiguration
        - --target-name=stateful-name
        - --target-kind=StatefulSet
        - --secret-dir=/etc/stash/repository/secret
        - --enable-cache=true
        - --max-connections=0
        - --metrics-enabled=true
        - --pushgateway-url=http://stash-stash-community.kube-system.svc:56789
        - --use-kubeapiserver-fqdn-for-aks=true
        - --enable-analytics=true
        - --logtostderr=true
        - --alsologtostderr=false
        - --v=3
        - --stderrthreshold=0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: appscode/stash:v0.12.3
        imagePullPolicy: IfNotPresent
        name: stash
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/stash
          name: stash-podinfo
        - mountPath: /etc/stash/repository/secret
          name: stash-secret-volume
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - python
        - template.py
        - /data/identities.json
        image: python:3-alpine
        imagePullPolicy: IfNotPresent
        name: config-templater
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /mounted
          name: templater
        workingDir: /mounted
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: stateful-name-templater
        name: templater
      - emptyDir: {}
        name: tmp-dir
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
        name: stash-podinfo
      - name: stash-secret-volume
        secret:
          defaultMode: 420
          secretName: stash-secret
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: stateful-name-647c9b7dc6
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updateRevision: stateful-name-647c9b7dc6
  updatedReplicas: 1
```
