### ISSUE TITLE
Issue with sidecar-based backup of a statefulset

### ISSUE THREAD

**Issue by johannesfritsch** [stashed/stash#1377]
we have setup a new cluster with k8s 1.21.4. We installed the latest version of stash according to the helm line (as of today)
with a trial license. The installation was without any problems. The job-based backups of our MySQL work fine.

When we now deploy our statefulsets (e.g. minio) (in the same way we did on some other cluster) we experience the following error:

![Screenshot 2021-08-26 at 14 43 37](https://user-images.githubusercontent.com/602587/130968393-6ce951c7-2ab1-4232-8fe9-45b1618e2aac.png)

The manifest is below. The variables are filled during deployment.

It looks like the operator is creating volumeMounts but is not creating the associated volumes in the statefulsets.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{namespace}}
  labels:
    app: minio
spec:
  serviceName: minio
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{minio.image}}
          imagePullPolicy: IfNotPresent
          args: ['server', '/export']
          volumeMounts:
            - name: export
              mountPath: /export
          ports:
            - name: service
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              value: "{{state.minioAccessKey.password}}"
            - name: MINIO_SECRET_KEY
              value: "{{state.minioSecretKey.password}}"
            - name: MINIO_BROWSER
              value: 'on'
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: service
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: export
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: {{minio.storageSpace}}Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{namespace}}
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: {{namespace}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Cache-Control: max-age=2592000";
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
    - hosts:
        - {{minio.host}}
      secretName: 'minio-{{namespace}}'
  rules:
    - host: {{minio.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 80
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: minio-repository
  namespace: {{namespace}}
spec:
  backend:
    s3:
      endpoint: https://backups.fan-platform.com
      bucket: {{namespace}}
      prefix: minio
    storageSecretName: backup-secret

---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: minio-backup
  namespace: {{namespace}}
spec:
  repository:
    name: minio-repository
  schedule: "*/15 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: minio
    volumeMounts:
    - name: export
      mountPath: /export
    paths:
    - /export
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  retentionPolicy:
    name: 'keep-backups'
    keepLast: 15
    keepHourly: 48
    keepDaily: 30
    keepWeekly: 4
    keepMonthly: 12
    keepYearly: 100
    prune: true
```
