### ISSUE TITLE
Add documentation on how to pass optional arguments to `restic` backup/restore command

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1384]
User can pass optional arguments to the restic backup/restore process via `spec.target.args` field of BackupConfiguration/RestoreSession.

**Pass args to restic backup command:**

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-deployment-backup
  namespace: demo
spec:
  repository:
    name: deployment-backup-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: sample-deployment
    volumeMounts:
      - name: source-data
        mountPath: /source/data
    paths:
      - /source/data
    args: ["--ignore-inode", "--tag=t1,t2"]
  retentionPolicy:
    name: "keep-last-5"
    keepLast: 5
    prune: true
```

**Pass args to restic restore command:**

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-deployment-restore
  namespace: demo
spec:
  repository:
    name: deployment-backup-repo
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: sample-deployment
    volumeMounts:
      - name: source-data
        mountPath: /source/data
    rules:
      - paths:
          - /source/data/
    args: ["--tag=t1,t2"]

```
