### ISSUE TITLE
Backup on OKD 4.10 not working due to missing finalizer permission

### ISSUE THREAD

**Issue by devops-42** [stashed/stash#1462]
Hi,

have setup a community edition of stash within an OKD 4.10 cluster (version: v2022.06.27, for v2022.07.09 I got ImagePullErrors). I created the `Repository` and the `BackupConfiguration` resources:

```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: foo
  namespace: example
spec:
  backend:
    s3:
      endpoint: my.s3.end.point
      bucket: my-bucket
      region: us-west-1
      prefix: /stash
    storageSecretName: s3-secret
```

```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: backup
  namespace: example
spec:
  repository:
    name: foo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: backup-test
    volumeMounts:
      - name: nginx-logs
        mountPath: /var/log/nginx
    paths:
      - /var/log/nginx
  retentionPolicy:
    name: "keep-last-5"
    keepLast: 5
    prune: true
```

Stash tries to trigger the cron job, but fails immediately:

```
operator W0714 12:54:40.968039       1 sidecar.go:214] Failed to inject stash sidecar into Deployment example/backup-test. Reason: rolebindings.rbac.authorization.k8s.io "stash-sidecar-deployment-backup-test" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

How can this be fixed?

Thanks for your help in advance!

Cheers
