### ISSUE TITLE
VolumeSnapshotter jobs conantyl failing

### ISSUE THREAD

**Issue by Lukier1** [stashed/stash#1473]
Hello, I have configured volume snapshotter to create snapshot of my pvc with instruction from docs. 
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: pvc-kafka-volume-snapshot
spec:
  schedule: "*/5 * * * *"
  driver: VolumeSnapshotter
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-0-kafka-cluster-kafka-0
    snapshotClassName: csi-hostpath-snapclass
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
``` 

The backup session is starting correctly, but never ends:
```
  
Every 1,0s: kubectl get backupsessions                                                                                                                                                                                                    
NAME                                               INVOKER-TYPE          INVOKER-NAME                            PHASE       DURATION   AGE
app-postgres-back-office-satelites-db-1661777100   BackupConfiguration   app-postgres-back-office-satelites-db   Succeeded   13s        4m36s
app-postgres-reservation-db-1661777100             BackupConfiguration   app-postgres-reservation-db             Succeeded   15s        4m36s
pvc-kafka-volume-snapshot-1661775600               BackupConfiguration   pvc-kafka-volume-snapshot               Running                29m
pvc-kafka-volume-snapshot-1661775900               BackupConfiguration   pvc-kafka-volume-snapshot               Skipped     1s         24m
pvc-kafka-volume-snapshot-1661776200               BackupConfiguration   pvc-kafka-volume-snapshot               Skipped     1s         19m
pvc-kafka-volume-snapshot-1661776500               BackupConfiguration   pvc-kafka-volume-snapshot               Skipped     1s         14m
```

I have found that crated job is failing due to error: 
```
F0829 12:20:02.075408       1 main.go:43] Error in Stash Main: the server could not find the requested resource (post volumesnapshots.snapshot.storage.k8s.io)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
	/src/vendor/k8s.io/klog/v2/klog.go:860 +0x8a
```

But  at my cluster I see that this resource exists: 
```
$ kubectl describe volumesnapshotcontents.snapshot.storage.k8s.io 
Name:         snapcontent-0ea0fbb6-668f-4045-adb8-53e5cfdb5720
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshotContent
```
I'm using stash enterprise version:  `stashed/stash-enterprise:v0.22.3`.

Do you know how to resolve this issue?  
I have found similar issue on github: https://github.com/stashed/stash/issues/1158.  In that issue, stash operator was expected `snapshot.storage.k8s.io/v1beta1` for `VolumeSnapshot`, is still required and stash operator doesn't support API `snapshot.storage.k8s.io/v1`  ?
