### ISSUE TITLE
BackupConfiguration tempDir doesn't seem to be used?

### ISSUE THREAD

**Issue by sgielen** [stashed/stash#1493]
I have this in my BackupConfiguration:

```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
spec:
  tempDir:
    medium: "Memory"
    sizeLimit: "512Mi"
```

According to https://stash.run/docs/v2022.09.29/concepts/crds/backupconfiguration/:

> Stash mounts an emptyDir for holding temporary files. It is also used for caching for faster backup performance. You can configure the emptyDir using spec.tempDir section.

However, the Pod has this as its `tmp-dir` Volume:

```
  - emptyDir:
      medium: Memory
      sizeLimit: 256Mi
    name: tmp-dir
```

I.e. the sizeLimit of 512Mi is not used when patching the Pod definition. Am I doing this wrong or is it a bug?

This is on Stash v0.22.3.
