### ISSUE TITLE
RestoreSession replicas logic

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#831]
Current Logic:
--------------
Presence of replicas field means, statefulset. So, ordinal added.

- replicas unset, should have same behavior as replicas:1.
- How is the `ordinal` suffix added?

**Comment by tamalsaha** [comment]
```yaml
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-pvc
  namespace: demo
spec:
  driver: VolumeSnapshotter
  target:
    replicas : 1
    volumeClaimTemplates:
      - metadata:
          nameTemplate: source-data-stash-demo-${POD_ORDINAL}
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 1Gi
          dataSource:
            kind: VolumeSnapshot
            name: src-pv-${POD_ORDINAL}-1560231666
            # name: ${CLAIM_NAME}-0-1560231666
            apiGroup: snapshot.storage.k8s.io
```
