### ISSUE TITLE
sidecar error: container's runAsUser breaks non-root policy

### ISSUE THREAD

**Issue by michaelkoetter** [stashed/stash#850]
I'm trying to run stash with prometheus-operator (installed from Helm chart).

It creates a sidecar container with the following security context:

```yaml
    securityContext:
      runAsGroup: 0
      runAsUser: 0
```

whereas the pod has this security context already:

```yaml
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
```

... which then leads to the error:

```yaml
    state:
      waiting:
        message: container's runAsUser breaks non-root policy
        reason: CreateContainerConfigError
```

Is there any way to change the sidecar's `runAsUser`/`runAsGroup` or omit them from the definition?

**Comment by hossainemruz** [comment]
@michaelkoetter It is not configurable in current release. However, we have already made it configurable for next release. We will release a rc in this week or next week.

**Comment by hossainemruz** [comment]
This should be fixed in Stash `0.9.0-rc.x`. If not fixed, feel free to reopen.

**Comment by sdelrio** [comment]
Similar issue with stable/loki-stack helm chart
* stash v0.9.0-rc.6
```
Events:
  Type     Reason          Age               From               Message
  ----     ------          ----              ----               -------
  Normal   Scheduled       70s               default-scheduler  Successfully assigned monitoring/loki-stack-0 to nuc1
  Normal   SandboxChanged  50s               kubelet, nuc1      Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          6s (x7 over 51s)  kubelet, nuc1      Container image "appscode/stash:v0.9.0-rc.6" already present on machine
  Warning  Failed          6s (x7 over 51s)  kubelet, nuc1      Error: container's runAsUser breaks non-root policy
```
* loki container
```
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

```
* stash container
```
    securityContext:
      runAsGroup: 0
      runAsUser: 0
```

* pod status
```
  initContainerStatuses:
  - image: appscode/stash:v0.9.0-rc.6
    imageID: ""
    lastState: {}
    name: stash-init
    ready: false
    restartCount: 0
    state:
      waiting:
        message: container's runAsUser breaks non-root policy
        reason: CreateContainerConfigError
```

**Comment by hossainemruz** [comment]
@sdelrio For backup, this is not expected. Can you please show the respective BackupConfiguration?

For restore, this is expected. Otherwise, the restored file could become read-only for your application. You must overwrite the default behavior by specifying `securityContext` in the `RestoreSession`. Please check this guide for more details: https://stash.run/docs/v0.9.0-rc.6/guides/latest/advanced-use-case/ownership/

**Comment by sdelrio** [comment]
```
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: s3-ss-restore-loki
  namespace: monitoring
spec:
  repository:
    name: s3-scw-repo-loki
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: loki-stack
    volumeMounts:
      - name: storage
        mountPath: /data
  rules:
  - paths:
    - /data
```

**Comment by hossainemruz** [comment]
>For restore, this is expected. Otherwise, the restored file could become read-only for your application. You must overwrite the default behavior by specifying securityContext in the RestoreSession. Please check this guide for more details: stash.run/docs/v0.9.0-rc.6/guides/latest/advanced-use-case/ownership

As I have already said that this is expected for RestoreSession. Please follow the linked guide to overwrite this behavior.

**Comment by sdelrio** [comment]
👍
```
NAME                 REPOSITORY         PHASE       AGE
s3-ss-restore-loki   s3-scw-repo-loki   Succeeded   29m
```

```
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: s3-ss-restore-loki
  namespace: monitoring
spec:
  repository:
    name: s3-scw-repo-loki
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: loki-stack
    volumeMounts:
      - name: storage
        mountPath: /data
  rules:
  - paths:
    - /data
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
```
