### ISSUE TITLE
RestoreSession stuck running

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#895]
I created a restore session, but it's stuck running.

The data I am trying to restore is just a tiny file. I am not seeing any errors in the stash logs.

```
k describe restoresession nginx-zb6h8-nginx-nginx -n nginx
Name:         nginx-zb6h8-nginx-nginx
Namespace:    nginx
Labels:       app=nginx-nginx
              chart=nginx-0.0.1
              heritage=Tiller
              io.cattle.field/appId=nginx-zb6h8
              release=nginx-zb6h8
Annotations:  <none>
API Version:  stash.appscode.com/v1beta1
Kind:         RestoreSession
Metadata:
  Creation Timestamp:  2019-09-05T18:43:43Z
  Finalizers:
    stash.appscode.com
  Generation:        1
  Resource Version:  1117480
  Self Link:         /apis/stash.appscode.com/v1beta1/namespaces/nginx/restoresessions/nginx-zb6h8-nginx-nginx
  UID:               16343d6e-d00d-11e9-865a-06d69e0f0b3e
Spec:
  Driver:  Restic
  Repository:
    Name:  nginx-zb6h8-nginx-restore-nginx
  Rules:
    Snapshots:
      e6d9e0da
  Target:
    Ref:
      API Version:  apps/v1beta1
      Kind:         Deployment
      Name:         nginx-zb6h8-nginx-nginx
    Volume Mounts:
      Mount Path:  /data
      Name:        test
Status:
  Phase:        Running
  Total Hosts:  1
Events:
  Type    Reason             Age    From                       Message
  ----    ------             ----   ----                       -------
  Normal  RestoreJobCreated  6m38s  RestoreSession Controller  restore job has been created succesfully for RestoreSession nginx/nginx-zb6h8-nginx-nginx
```

**Comment by hossainemruz** [comment]
I believe this will be fixed by this PR: https://github.com/stashed/stash/pull/891

**Comment by codejamninja** [comment]
Ok, nice. Is there a rough ETA?

**Comment by hossainemruz** [comment]
Probably next week.

**Comment by codejamninja** [comment]
Cool, thanks!

**Comment by codejamninja** [comment]
I'll keep it open until then

**Comment by hossainemruz** [comment]
sure

**Comment by codejamninja** [comment]
I added `paths` to the target and changes the apiVersion from `apps/v1beta` to `apps/v1` and it fixed this issue.

#### Before
```
  target:
    ref:
      apiVersion: apps/v1beta
      kind: Deployment
      name: {{ template "gitlab.fullname" . }}-gitlab
    volumeMounts:
      - name: data
        mountPath: /_data
```

#### After
```
  target:
    paths:
      /_data
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ template "gitlab.fullname" . }}-gitlab
    volumeMounts:
      - name: data
        mountPath: /_data
```
