### ISSUE TITLE
Can't restore snapshot if repository name doesn't start with deployment

### ISSUE THREAD

**Issue by fastlorenzo** [stashed/stash#908]
I tried to restore a snapshot today and encountered a bug while doing so:

I had to prepend `deployment` to the name of the repository to create the recovery or the admission webhook is saying the repository doesn't exist:

`admission webhook "recovery.admission.stash.appscode.com" denied the request: invalid repository name`

If I don't, the repository is successfully created, but then I have the following error:

```
Events:
  Type     Reason                     Age   From            Message
  ----     ------                     ----  ----            ------- 
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
  Warning  RecoveryJobFailedToCreate  13m   stash-recovery  repositories.stash.appscode.com "deployment.s3-repo-odoo-gyevents" not found
```

Below is my repository config:
```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo-odoo-gyevents
  namespace: default
spec:
  backend:
    s3:
      endpoint: s3.amazonaws.com # use server URL for s3 compatible other storage service
      bucket: stash-backup-k8s
      prefix: /backup/odoo-gyevents
    storageSecretName: stash-s3-secret
```

And the backup configuration:
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup-odoo-gyevents
  namespace: default
spec:
  repository:
    name: s3-repo-odoo-gyevents
  schedule: "0 */12 * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: odoo-gyevents-deployment
    volumeMounts:
    - name: odoo-gyevents-odoo-data-storage
      mountPath: /var/lib/odoo
    - name: odoo-gyevents-psql-data-storage
      mountPath: /var/lib/postgresql
    paths:
    - /var/lib/odoo
    - /var/lib/postgresql
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

You can see below that the snapshots were successfully created:
```
~ kubectl get snapshots
NAME                             AGE 
s3-repo-odoo-gyevents-2c4a957e   13h
s3-repo-odoo-gyevents-2ceb55d9   13h
s3-repo-odoo-gyevents-89c1579b   12h
s3-repo-odoo-gyevents-9cb700dd   12h
s3-repo-odoo-gyevents-69989b3f   11h
s3-repo-odoo-gyevents-46f54a6a   11h
s3-repo-odoo-gyevents-c5eb2443   10h
s3-repo-odoo-gyevents-7f45a144   10h
s3-repo-odoo-gyevents-72359441   9h
s3-repo-odoo-gyevents-9d44c5a3   9h 
```

And you can see as well that the repository does exist:
```
~ kubectl get repository 
NAME                    INTEGRITY   SIZE         SNAPSHOT-COUNT   LAST-SUCCESSFUL-BACKUP   AGE 
s3-repo-odoo-gyevents   true        34.344 MiB   10               9h                       34h
```

Below is the configuration for the recovery job:
```
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: recover-psql
  namespace: default
spec:
  repository:
    name: s3-repo-odoo-gyevents
    namespace: default
  snapshot: s3-repo-odoo-gyevents-2c4a957e
  paths:
  - /var/lib/postgresql
  recoveredVolumes:
  - mountPath: /var/lib/postgresql
    persistentVolumeClaim:
      claimName: odoo-gyevents-psql-data-storage
```

It looks like the admission webhook is checking for a repository name that starts with `deployment.`, but the actual recovery job is checking for the exact name of the repository.
