### ISSUE TITLE
stash's PodSecurityPolicy is not used because of alphabetical order

### ISSUE THREAD

**Issue by blacs30** [stashed/stash#910]
> My setup: I use the helm chart 0.9.0-rc.0 on a baremetal Kubernetes 1.15.4 3 node cluster installed with kubespray.

The error message which I get is: 

`Error: container has runAsNonRoot and image will run as root`  and a status of `CreateContainerConfigError`. 

- The stash container starts fine but the prom/pushgateway doesn't.
- The PSP's seemed fine. 
- Running `kubectl auth can-i use psp.policy/stash --as=system:serviceaccount:stash:stash` results to *yes*

Then I noticed that the default restricted PSP is named `restricted` which comes alphabetically first and then the `stash-*` PSP follows if I understood the [Kubernetes documentation](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order) correct.

The restricted PSP was installed via kubespray but also in most tutorials it is named this way.

1. I don't know if that pod really needs to run as root, probably not.

Anyway, I think that the PSP's should come first in the alphabet before the letter r, assuming that many have the restricted PSP.

Another question from my side is how this works in this case is regarding  the helm chart [stash/templates/cluster-role.yaml](https://github.com/stashed/installer/blob/48f2f3be41cacc1ae833389db149d3d35bac86fd/chart/stash/templates/cluster-role.yaml#L108)

2. How is it decided which PSP to use? E.g. how is it possible that the `stash-backupsession-cron-psp` is used and not the plain `stash` PSP? 

In most instances I have seen so far separate ServiceAccounts have separate Roles (with the dedicated PSP) and RoleBindings.

**Comment by uipo78** [comment]
I'm getting the same behavior as the OP. I'm guessing what we're seeing is a result of the fact that the pod security policies provided by Stash are, for some reason, not enough to allow a pod to be created without a mutation of a `securityContext`.

According to [the docs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order), the first PodSecurityPolicy ordered by name is selected only if a pod must be defaulted or mutated. In my case, I notice that the `securityContext` of the operator pod (as well as other job-related pods) is mutated such that it looks like this:
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
      drop:
      - ALL
  runAsNonRoot: true
```

Again, that `securityContext` does not exist in the parent deployment's `podSpec` section.

**Comment by uipo78** [comment]
@hossainemruz have you seen this before when installing stash on a cluster with PodSecurityPolicies enabled?

**Comment by uipo78** [comment]
...hello?

**Comment by hossainemruz** [comment]
We haven't tried to reproduce this issue yet.

**Comment by uipo78** [comment]
Just to keep this ticket alive, this problem still exists in the latest release `v0.9.0-rc6`.

**Comment by uipo78** [comment]
I can't even install `0.9.0-rc6` in my PSP enabled cluster without fudging with PSP-related things. And once the operator pod is actually able to start up properly, the problem brought up in this issue makes it so that stash is effectively nonfunctional.

This checkmark in the [README](https://github.com/stashed/stash#features) clearly states that stash should be able to run on a PSP-enabled cluster, but has anyone actually verified this? The problems addressed in this issue aren't provider-specific.
![image](https://user-images.githubusercontent.com/22528346/82470959-a6ee7b00-9a8b-11ea-9a28-681bafdf1a8a.png)

**Comment by blacs30** [comment]
I use Helm but overwrite/change psp related things after templating it. I never liked the idea of helm install, so it’s fine for me.

**Comment by tamalsaha** [comment]
@uipo78 , how did you provision the cluster? Can you please give us a reproducible steps (preferably using kind) so we can test and fix this?

**Comment by tamalsaha** [comment]
@uipo78 , does your cluster have a cluster role binding that gives every service account permission to `use` the `restricted` psp?

**Comment by tamalsaha** [comment]
I see the problem. In Kubespray, `*podsecuritypolicy_enabled* - When set to `true`, enables the PodSecurityPolicy admission controller and defines two policies `privileged` (applying to all resources in `kube-system` namespace and kubelet) and `restricted` (applying all other namespaces).`

https://github.com/kubernetes-sigs/kubespray/blob/release-2.13/roles/kubernetes-apps/cluster_roles/templates/psp-crb.yml.j2#L10-L13

When multiple PSP-s are eligible, k8s sorts those by name and applies the first one. So, here restricted in getting selected.

**Comment by tamalsaha** [comment]
The solution we are leaning towards is using the new `baseline` psp as described here: https://kubernetes.io/docs/concepts/security/pod-security-standards/#policy-instantiation

This comes before restricted and has the necessary permissions stash needs.

**Comment by tamalsaha** [comment]
The fixes are working for me with the baseline psp.

```
~/g/s/s/installer (psp) $ kubectl get pods stash-7fd59b5cc9-fvxs2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/apiregistration.yaml: 9609ec27eddb2690bbb7c22e946324d9e3de03415cc4ca6a6e3f7835054641ca
    kubernetes.io/psp: baseline
  creationTimestamp: "2020-06-01T18:55:11Z"
  generateName: stash-7fd59b5cc9-
  labels:
    app.kubernetes.io/instance: stash
    app.kubernetes.io/name: stash
    pod-template-hash: 7fd59b5cc9

```
