### ISSUE TITLE
"setup option for repository fail"

### ISSUE THREAD

**Issue by drallgood** [stashed/stash#951]
I'm getting this rather unhelpful error message:
`Backup session failed to complete. Reason: backup failed for host: host-0. Reason: failed to complete backup for host host-0. Reaosn: setup option for repository fail`

Any idea what this might be?
I followed the tutorial for 0.9.0.rc2 in the docs but used b2 instead of GCE.

**Comment by hossainemruz** [comment]
Can you please share the YAML for Repository and BackupConfiguration?

**Comment by drallgood** [comment]
Sure.

```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: b2-repo
  namespace: wp-th
spec:
  backend:
    b2:
      bucket: pbda-backup
      prefix: /kubernetes/
    storageSecretName: b2-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: wp-th
spec:
  repository:
    name: b2-repo
  schedule: "*/2 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: wp-th
    volumeMounts:
    - name: techhangout-data
      mountPath: /var/www/html
    paths:
    - /var/www/html
  retentionPolicy:
    name: 'smart'
    keepDaily: 7
    keepWeekly: 4
    keepMonthly: 6
    keepYearly: 7
    prune: true
```
