### ISSUE TITLE
Backup History Limit not working

### ISSUE THREAD

**Issue by cwrau** [stashed/stash#959]
The following config:

```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: test-backup
  namespace: ingress
spec:
  #  task:
  #    name: pvc-backup
  backupHistoryLimit: 10
  repository:
    name: minio-files
    namespace: backup
  schedule: "*/1 * * * *"
  target:
    ref:
      #      apiVersion: v1
      #      kind: PersistentVolumeClaim
      #      name: test
      apiVersion: apps/v1
      kind: Deployment
      name: test
    volumeMounts:
    - name: test
      mountPath: /test
    paths:
    - /test
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

Does not seem to delete it's backup sessions (and it's backup jobs) when there are more than 10:

```
λ k -n ingress get backupsessions.stash.appscode.com -l stash.appscode.com/backup-configuration=test-backup
NAME                     BACKUPCONFIGURATION   PHASE       AGE
test-backup-1572973132   test-backup           Succeeded   12m
test-backup-1572973152   test-backup           Succeeded   12m
test-backup-1572973215   test-backup           Succeeded   11m
test-backup-1572973263   test-backup           Succeeded   10m
test-backup-1572973324   test-backup           Succeeded   9m33s
test-backup-1572973385   test-backup           Succeeded   8m31s
test-backup-1572973445   test-backup           Succeeded   7m32s
test-backup-1572973507   test-backup           Succeeded   6m30s
test-backup-1572973567   test-backup           Succeeded   5m29s
test-backup-1572973629   test-backup           Succeeded   4m28s
test-backup-1572973691   test-backup           Succeeded   3m26s
test-backup-1572973751   test-backup           Succeeded   2m26s
test-backup-1572973812   test-backup           Succeeded   85s
test-backup-1572973873   test-backup           Succeeded   24s
```
```
λ k -n ingress get backupsessions.stash.appscode.com -l stash.appscode.com/backup-configuration=test-backup | wc -l
15
```
