### ISSUE TITLE
Cannot deploy stash and stash-postgres from the same chart

### ISSUE THREAD

**Issue by ljani** [stashed/stash#991]
I have a helm v2 chart with following `requirements.yaml`:

```
dependencies:
- name: stash
  version: v0.9.0-rc.2
  repository: "https://charts.appscode.com/stable/"
- name: stash-postgres
  version: 10.6
  repository: "https://charts.appscode.com/stable/"
```

However, I cannot deploy that chart. It fails with the following error:

```
 Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "Function" in version "stash.appscode.com/v1beta1", unable to recognize "": no matches for kind "Function" in version "stash.appscode.com/v1beta1", unable to recognize "": no matches for kind "Task" in version "stash.appscode.com/v1beta1", unable to recognize "": no matches for kind "Task" in version "stash.appscode.com/v1beta1"]
```

I think it's because `stash` has not been deployed to the cluster yet and Helm is trying to verify all the CRDs exist. Other repositories seem to be using a separate yaml file for CRDs to be applied before installation as a workaround.

Is it safe to deploy the CRDs from [here](https://github.com/stashed/stash/tree/v0.9.0-rc.2/api/crds) manually, before installing the chart?

My use case is to create a helm chart, which can be used to bootstrap new Kubernetes clusters. It'll contain `stash`, `nginx-ingress`, `cert-manager`, etc. common tools for the cluster.
